C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2010-AfterAllTheStoryGoes-01-HereWeAre.wav -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="After all the story goes" -metadata disc="2" -metadata date="2010" -metadata track="1" -metadata title="Here we are" -c:a flac MuffinsZebulon-2010-AfterAllTheStoryGoes-01-HereWeAre.flac
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2010-AfterAllTheStoryGoes-02-LongAgo.wav -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="After all the story goes" -metadata disc="2" -metadata date="2010" -metadata track="2" -metadata title="Long ago"  -c:a flac MuffinsZebulon-2010-AfterAllTheStoryGoes-02-LongAgo.flac
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2010-AfterAllTheStoryGoes-03-MyDad.wav -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="After all the story goes" -metadata disc="2" -metadata date="2010" -metadata track="3" -metadata title="My Dad"  -c:a flac MuffinsZebulon-2010-AfterAllTheStoryGoes-03-MyDad.flac
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2010-AfterAllTheStoryGoes-04-YoullBePartOfMyWorld.wav -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="After all the story goes" -metadata disc="2" -metadata date="2010" -metadata track="4" -metadata title="You'll be part of my world"  -c:a flac MuffinsZebulon-2010-AfterAllTheStoryGoes-04-YoullBePartOfMyWorld.flac
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2010-AfterAllTheStoryGoes-05-TypicalPostcard.wav -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="After all the story goes" -metadata disc="2" -metadata date="2010" -metadata track="5" -metadata title="Typical postcard"  -c:a flac MuffinsZebulon-2010-AfterAllTheStoryGoes-05-TypicalPostcard.flac
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2010-AfterAllTheStoryGoes-06-IHadEnough.wav -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="After all the story goes" -metadata disc="2" -metadata date="2010" -metadata track="6" -metadata title="I had enough"  -c:a flac MuffinsZebulon-2010-AfterAllTheStoryGoes-06-IHadEnough.flac
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2010-AfterAllTheStoryGoes-07-ManyYearsFromNow.wav -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="After all the story goes" -metadata disc="2" -metadata date="2010" -metadata track="7" -metadata title="Many years from now"  -c:a flac MuffinsZebulon-2010-AfterAllTheStoryGoes-07-ManyYearsFromNow.flac
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2010-AfterAllTheStoryGoes-08-PreciousOne.wav -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="After all the story goes" -metadata disc="2" -metadata date="2010" -metadata track="8" -metadata title="Precious one"  -c:a flac MuffinsZebulon-2010-AfterAllTheStoryGoes-08-PreciousOne.flac
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2010-AfterAllTheStoryGoes-09-WantItNow.wav -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="After all the story goes" -metadata disc="2" -metadata date="2010" -metadata track="9" -metadata title="Want it now"  -c:a flac MuffinsZebulon-2010-AfterAllTheStoryGoes-09-WantItNow.flac
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2010-AfterAllTheStoryGoes-10-SuchAMess.wav -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="After all the story goes" -metadata disc="2" -metadata date="2010" -metadata track="10" -metadata title="Such a mess"  -c:a flac MuffinsZebulon-2010-AfterAllTheStoryGoes-10-SuchAMess.flac
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2010-AfterAllTheStoryGoes-11-Travel.wav -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="After all the story goes" -metadata disc="2" -metadata date="2010" -metadata track="11" -metadata title="Travel"  -c:a flac MuffinsZebulon-2010-AfterAllTheStoryGoes-11-Travel.flac
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2010-AfterAllTheStoryGoes-12-AfterAllTheStoryGoes.wav -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="After all the story goes" -metadata disc="2" -metadata date="2010" -metadata track="12" -metadata title="After all the story goes"  -c:a flac MuffinsZebulon-2010-AfterAllTheStoryGoes-12-AfterAllTheStoryGoes.flac
