C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2000-MuffinsZebulon-01-ThankYouToBeHere.wav -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Muffin's Zebulon" -metadata disc="1" -metadata date="2000" -metadata track="1" -metadata title="Thank you to be here" -c:a flac MuffinsZebulon-2000-MuffinsZebulon-01-ThankYouToBeHere.flac
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2000-MuffinsZebulon-02-KingForADay.wav -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Muffin's Zebulon" -metadata disc="1" -metadata date="2000" -metadata track="2" -metadata title="King for a day"  -c:a flac MuffinsZebulon-2000-MuffinsZebulon-02-KingForADay.flac
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2000-MuffinsZebulon-03-Bitterness.wav -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Muffin's Zebulon" -metadata disc="1" -metadata date="2000" -metadata track="3" -metadata title="Bitterness"  -c:a flac MuffinsZebulon-2000-MuffinsZebulon-03-Bitterness.flac
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2000-MuffinsZebulon-04-WhenWeGetOld.wav -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Muffin's Zebulon" -metadata disc="1" -metadata date="2000" -metadata track="4" -metadata title="When we get old"  -c:a flac MuffinsZebulon-2000-MuffinsZebulon-04-WhenWeGetOld.flac
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2000-MuffinsZebulon-05-LuckyBreak.wav -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Muffin's Zebulon" -metadata disc="1" -metadata date="2000" -metadata track="5" -metadata title="Lucky break"  -c:a flac MuffinsZebulon-2000-MuffinsZebulon-05-LuckyBreak.flac
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2000-MuffinsZebulon-06-RailsOfYourLife.wav -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Muffin's Zebulon" -metadata disc="1" -metadata date="2000" -metadata track="6" -metadata title="Rails of your life"  -c:a flac MuffinsZebulon-2000-MuffinsZebulon-06-RailsOfYourLife.flac
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2000-MuffinsZebulon-07-SecondFloor.wav -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Muffin's Zebulon" -metadata disc="1" -metadata date="2000" -metadata track="7" -metadata title="Second floor"  -c:a flac MuffinsZebulon-2000-MuffinsZebulon-07-SecondFloor.flac
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2000-MuffinsZebulon-08-WhenYouFindLove.wav -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Muffin's Zebulon" -metadata disc="1" -metadata date="2000" -metadata track="8" -metadata title="When you find love"  -c:a flac MuffinsZebulon-2000-MuffinsZebulon-08-WhenYouFindLove.flac
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2000-MuffinsZebulon-09-ItDoesntBeginEasy.wav -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Muffin's Zebulon" -metadata disc="1" -metadata date="2000" -metadata track="9" -metadata title="It doesn't begin easy"  -c:a flac MuffinsZebulon-2000-MuffinsZebulon-09-ItDoesntBeginEasy.flac
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2000-MuffinsZebulon-10-DontEverStayAlone.wav -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Muffin's Zebulon" -metadata disc="1" -metadata date="2000" -metadata track="10" -metadata title="Don't ever stay alone"  -c:a flac MuffinsZebulon-2000-MuffinsZebulon-10-DontEverStayAlone.flac
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2000-MuffinsZebulon-11-ThankYouOnceAgain.wav -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Muffin's Zebulon" -metadata disc="1" -metadata date="2000" -metadata track="11" -metadata title="Thank you once again"  -c:a flac MuffinsZebulon-2000-MuffinsZebulon-11-ThankYouOnceAgain.flac
