REM https://buzut.net/gerer-les-metadatas-id3-avec-ffmpeg/
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2021-TimesRoll-01-TimesGoinBy.wav -i MuffinsZebulon-2021-TimesRoll_575.png -map 0 -map 1:0 -id3v2_version 3 -b:a 192k -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Times'n Roll" -metadata disc="3" -metadata date="2021" -metadata track="1" -metadata title="Time's goin by" MuffinsZebulon-2021-TimesRoll-01-TimesGoinBy.mp3

C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2021-TimesRoll-02-Vinaigre.wav -i MuffinsZebulon-2021-TimesRoll_575.png -map 0 -map 1:0 -id3v2_version 3 -b:a 192k -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Times'n Roll" -metadata disc="3" -metadata date="2021" -metadata track="2" -metadata title="Vinaigre" MuffinsZebulon-2021-TimesRoll-02-Vinaigre.mp3

C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2021-TimesRoll-03-GirlAndBoy.wav -i MuffinsZebulon-2021-TimesRoll_575.png -map 0 -map 1:0 -id3v2_version 3 -b:a 192k -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Times'n Roll" -metadata disc="3" -metadata date="2021" -metadata track="3" -metadata title="Girl and Boy" MuffinsZebulon-2021-TimesRoll-03-GirlAndBoy.mp3

C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2021-TimesRoll-04-IllBeHere.wav -i MuffinsZebulon-2021-TimesRoll_575.png -map 0 -map 1:0 -id3v2_version 3 -b:a 192k -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Times'n Roll" -metadata disc="3" -metadata date="2021" -metadata track="4" -metadata title="I'll be here" MuffinsZebulon-2021-TimesRoll-04-IllBeHere.mp3

C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2021-TimesRoll-05-OneMoreYear.wav -i MuffinsZebulon-2021-TimesRoll_575.png -map 0 -map 1:0 -id3v2_version 3 -b:a 192k -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Times'n Roll" -metadata disc="3" -metadata date="2021" -metadata track="5" -metadata title="One more year" MuffinsZebulon-2021-TimesRoll-05-OneMoreYear.mp3

C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2021-TimesRoll-06-ItsTimeForYou.wav -i MuffinsZebulon-2021-TimesRoll_575.png -map 0 -map 1:0 -id3v2_version 3 -b:a 192k -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Times'n Roll" -metadata disc="3" -metadata date="2021" -metadata track="6" -metadata title="It's time for you" MuffinsZebulon-2021-TimesRoll-06-ItsTimeForYou.mp3

C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2021-TimesRoll-07-Virus.wav -i MuffinsZebulon-2021-TimesRoll_575.png -map 0 -map 1:0 -id3v2_version 3 -b:a 192k -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Times'n Roll" -metadata disc="3" -metadata date="2021" -metadata track="7" -metadata title="Virus" MuffinsZebulon-2021-TimesRoll-07-Virus.mp3

C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2021-TimesRoll-08-Alien.wav -i MuffinsZebulon-2021-TimesRoll_575.png -map 0 -map 1:0 -id3v2_version 3 -b:a 192k -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Times'n Roll" -metadata disc="3" -metadata date="2021" -metadata track="8" -metadata title="Alien" MuffinsZebulon-2021-TimesRoll-08-Alien.mp3

C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2021-TimesRoll-09-BadJoke.wav -i MuffinsZebulon-2021-TimesRoll_575.png -map 0 -map 1:0 -id3v2_version 3 -b:a 192k -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Times'n Roll" -metadata disc="3" -metadata date="2021" -metadata track="9" -metadata title="Bad joke" MuffinsZebulon-2021-TimesRoll-09-BadJoke.mp3

C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2021-TimesRoll-10-MysteryGirl.wav -i MuffinsZebulon-2021-TimesRoll_575.png -map 0 -map 1:0 -id3v2_version 3 -b:a 192k -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Times'n Roll" -metadata disc="3" -metadata date="2021" -metadata track="10" -metadata title="Mystery girl" MuffinsZebulon-2021-TimesRoll-10-MysteryGirl.mp3

C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2021-TimesRoll-11-AVeryGoodMum.wav -i MuffinsZebulon-2021-TimesRoll_575.png -map 0 -map 1:0 -id3v2_version 3 -b:a 192k -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Times'n Roll" -metadata disc="3" -metadata date="2021" -metadata track="11" -metadata title="A very good mum" MuffinsZebulon-2021-TimesRoll-11-AVeryGoodMum.mp3
