REM https://buzut.net/gerer-les-metadatas-id3-avec-ffmpeg/
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2000-MuffinsZebulon-01-ThankYouToBeHere.wav -i MuffinsZebulon-2000-MuffinsZebulon_575.png -map 0 -map 1:0 -id3v2_version 3 -b:a 192k -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Muffin's Zebulon" -metadata disc="1" -metadata date="2000" -metadata track="1" -metadata title="Thank you to be here" MuffinsZebulon-2000-MuffinsZebulon-01-ThankYouToBeHere.mp3
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2000-MuffinsZebulon-02-KingForADay.wav -i MuffinsZebulon-2000-MuffinsZebulon_575.png -map 0 -map 1:0 -id3v2_version 3 -b:a 192k -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Muffin's Zebulon" -metadata disc="1" -metadata date="2000" -metadata track="2" -metadata title="King for a day" MuffinsZebulon-2000-MuffinsZebulon-02-KingForADay.mp3
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2000-MuffinsZebulon-03-Bitterness.wav -i MuffinsZebulon-2000-MuffinsZebulon_575.png -map 0 -map 1:0 -id3v2_version 3 -b:a 192k -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Muffin's Zebulon" -metadata disc="1" -metadata date="2000" -metadata track="3" -metadata title="Bitterness" MuffinsZebulon-2000-MuffinsZebulon-03-Bitterness.mp3
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2000-MuffinsZebulon-04-WhenWeGetOld.wav -i MuffinsZebulon-2000-MuffinsZebulon_575.png -map 0 -map 1:0 -id3v2_version 3 -b:a 192k -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Muffin's Zebulon" -metadata disc="1" -metadata date="2000" -metadata track="4" -metadata title="When we get old" MuffinsZebulon-2000-MuffinsZebulon-04-WhenWeGetOld.mp3
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2000-MuffinsZebulon-05-LuckyBreak.wav -i MuffinsZebulon-2000-MuffinsZebulon_575.png -map 0 -map 1:0 -id3v2_version 3 -b:a 192k -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Muffin's Zebulon" -metadata disc="1" -metadata date="2000" -metadata track="5" -metadata title="Lucky break" MuffinsZebulon-2000-MuffinsZebulon-05-LuckyBreak.mp3
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2000-MuffinsZebulon-06-RailsOfYourLife.wav -i MuffinsZebulon-2000-MuffinsZebulon_575.png -map 0 -map 1:0 -id3v2_version 3 -b:a 192k -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Muffin's Zebulon" -metadata disc="1" -metadata date="2000" -metadata track="6" -metadata title="Rails of your life" MuffinsZebulon-2000-MuffinsZebulon-06-RailsOfYourLife.mp3
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2000-MuffinsZebulon-07-SecondFloor.wav -i MuffinsZebulon-2000-MuffinsZebulon_575.png -map 0 -map 1:0 -id3v2_version 3 -b:a 192k -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Muffin's Zebulon" -metadata disc="1" -metadata date="2000" -metadata track="7" -metadata title="Second floor" MuffinsZebulon-2000-MuffinsZebulon-07-SecondFloor.mp3
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2000-MuffinsZebulon-08-WhenYouFindLove.wav -i MuffinsZebulon-2000-MuffinsZebulon_575.png -map 0 -map 1:0 -id3v2_version 3 -b:a 192k -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Muffin's Zebulon" -metadata disc="1" -metadata date="2000" -metadata track="8" -metadata title="When you find love" MuffinsZebulon-2000-MuffinsZebulon-08-WhenYouFindLove.mp3
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2000-MuffinsZebulon-09-ItDoesntBeginEasy.wav -i MuffinsZebulon-2000-MuffinsZebulon_575.png -map 0 -map 1:0 -id3v2_version 3 -b:a 192k -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Muffin's Zebulon" -metadata disc="1" -metadata date="2000" -metadata track="9" -metadata title="It doesn't begin easy" MuffinsZebulon-2000-MuffinsZebulon-09-ItDoesntBeginEasy.mp3
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2000-MuffinsZebulon-10-DontEverStayAlone.wav -i MuffinsZebulon-2000-MuffinsZebulon_575.png -map 0 -map 1:0 -id3v2_version 3 -b:a 192k -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Muffin's Zebulon" -metadata disc="1" -metadata date="2000" -metadata track="10" -metadata title="Don't ever stay alone" MuffinsZebulon-2000-MuffinsZebulon-10-DontEverStayAlone.mp3
C:\prog\ffmpeg-4.0.2-win64-static\bin\ffmpeg.exe -i MuffinsZebulon-2000-MuffinsZebulon-11-ThankYouOnceAgain.wav -i MuffinsZebulon-2000-MuffinsZebulon_575.png -map 0 -map 1:0 -id3v2_version 3 -b:a 192k -metadata genre="Pop Rock" -metadata artist="Muffin's Zebulon" -metadata album="Muffin's Zebulon" -metadata disc="1" -metadata date="2000" -metadata track="11" -metadata title="Thank you once again" MuffinsZebulon-2000-MuffinsZebulon-11-ThankYouOnceAgain.mp3
